language: julia
os:
  - linux
  - osx
  - windows
env:
  - DATADEPS_ALWAYS_ACCEPT=true
julia:
  - 1.3
  - 1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      julia: 1.3
    - os: windows
      julia: 1.3
    - os: osx
      julia: nightly
    - os: windows
      julia: nightly
  fast_finish: true
branches:
  only:
    - master
    - /release-.*/
notifications:
  email: false
